apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one-metadata-name
  labels:
    app: app-one-label

spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-one-label

  template:
    metadata:
      labels:
        app: app-one-label

    spec:
      containers:
        - name: app-one-container
          image: phaneindra/sample-java-app:latest
          ports:
          - containerPort: 8080
      # imagePullSecrets:
      # - name: docker-hub