apiVersion: v1
kind: Service
metadata:
  name: app-one-metadata-name
  labels:
    app: app-one-label
spec:
  type: NodePort
  ports:
  - nodePort: 30000
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: app-one-label