apiVersion: v1
kind: Pod
metadata:
  name: build-pod
  labels:
    name: ci-app
spec:
  containers:
  - name: maven
    image: maven:3.5.4-jdk-8-slim
    command:
      - "tail -f /dev/null"
    imagePullPolicy: Always
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1024m" 
  - name: docker
    image: docker:18.06.1
    command: ["tail", "-f", "/dev/null"]
    imagePullPolicy: Always
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1024m" 
    volumeMounts:
      - name: docker
        mountPath: /var/run/docker.sock # We use the k8s host docker engine
