spring:
  application:
    name: app1
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server.binarybutter.com/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
  info:
    app:
      name: app1