spring:
  application:
    name: app1
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server.binarybutter.com/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    hostname: localhost

info:
  app:
    name: app1
    description: /hello endpoint check
    app-version: 0.0.1
